parameters:
    # import modifier test class.
    ongr_connections.import.modifier.class: ONGR\ConnectionsBundle\Tests\Functional\Fixtures\ImportCommandTest\TestModifyEventListener
    # sync execute test class.
    ongr_connections.sync.execute.modifier.class: ONGR\ConnectionsBundle\Tests\Functional\Fixtures\SyncCommandsTest\TestModifyEventListener
    # binlog parameters
    ongr_connections.sync.diff_provider.binlog_dir: /var/lib/mysql
    ongr_connections.sync.diff_provider.binlog_basename: mysql-bin
