parameters:
    shop_ids:
        - 0

imports:
    - { resource: project_defaults.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:          { asset_reset: %asset_reset%, top_cms_links: %top_cms_links% }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - ONGRDemoBundle
    java: "%java_path%"
    filters:
        cssrewrite: ~
        sass: ~
        compass: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
    assets:
        demo_css:
            inputs:
                - "@ONGRDemoBundle/Resources/public/style/ongr.scss"
            filters:
                - compass
        demo_js:
            inputs:
                - "@ONGRDemoBundle/Resources/public/scripts/**/*.js"
                - "@ONGRDemoBundle/Resources/public/scripts/main.js"
            filters:
                - closure


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            ONGROXIDConnectorBundle:
                type: annotation
                alias: OXIDConnectorBundle
                dir: Entity
                prefix: ONGR\OXIDConnectorBundle\Entity
                is_bundle: true
            ONGRDemoOXIDBundle:
                type: annotation
                alias: DemoOXIDBundle
                dir: Entity
                prefix: ONGR\DemoOXIDBundle\Entity
                is_bundle: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ongr_content:
    es:
        repositories:
            product: es.manager.oxid.productdocument
            content: es.manager.oxid.contentdocument
            category: es.manager.oxid.categorydocument
    category_root_id: oxrootid

ongr_router:
    es_manager: oxid
    seo_routes:
        product:
            _route: ongr_product
            _controller: ONGRDemoBundle:Product:document
            _default_route: ongr_product_show
            _id_param: id
        category:
            _route: ongr_category
            _default_route: ongr_category_show
            _id_param: id
            _controller: ONGRDemoBundle:Category:document
        content:
            _route: ongr_content
            _default_route: ongr_content
            _id_param: document
            _controller: ONGRDemoBundle:Content:document

ongr_elasticsearch:
    connections:
        default:
            hosts:
                - { host: "%es_host%" }
            index_name: "%es_index_name%"
            settings:
                number_of_shards: "%es_number_of_shards%"
                number_of_replicas: "%es_number_of_replicas%"
                index:
                    refresh_interval: "%es_refresh_interval%"
                analysis:
                    tokenizer:
                        pathTokenizer:
                            type : path_hierarchy
                            buffer_size: 2024
                            skip: 0
                            delimiter: /
                    filter:
                        incremental_filter:
                            type: edge_ngram
                            min_gram: 1
                            max_gram: 20
                    analyzer:
                        indexAnalyzer:
                            type: snowball
                            language: German2
                            stopwords: "der,die,das,mit,und,f端r"
                        searchAnalyzer:
                            type: snowball
                            language: German2
                            stopwords: "der,die,das,mit,und,f端r"
                        pathAnalyzer:
                            type: custom
                            tokenizer: pathTokenizer
                        urlAnalyzer:
                            type: custom
                            tokenizer: keyword
                            filter: [lowercase]
                        incrementalAnalyzer:
                            type: custom
                            tokenizer: standard
                            filter:
                                - lowercase
                                - incremental_filter
        oxid:
            hosts:
                - { host: 127.0.0.1:9200 }
            index_name: ongr_oxid
            settings:
                number_of_shards: 2
                number_of_replicas: 0
                index:
                    refresh_interval: -1
                analysis:
                    tokenizer:
                        pathTokenizer:
                            type : path_hierarchy
                            buffer_size: 2024
                            skip: 0
                            delimiter: /
                    filter:
                        incremental_filter:
                            type: edge_ngram
                            min_gram: 1
                            max_gram: 20
                    analyzer:
                        indexAnalyzer:
                            type: snowball
                            language: German2
                            stopwords: "der,die,das,mit,und,f端r"
                        searchAnalyzer:
                            type: snowball
                            language: German2
                            stopwords: "der,die,das,mit,und,f端r"
                        pathAnalyzer:
                            type: custom
                            tokenizer: pathTokenizer
                        urlAnalyzer:
                            type: custom
                            tokenizer: keyword
                            filter: [lowercase]
                        incrementalAnalyzer:
                            type: custom
                            tokenizer: standard
                            filter:
                                - lowercase
                                - incremental_filter
    managers:
        default:
            connection: default
            debug: "%kernel.debug%"
            mappings:
                - ONGRDemoBundle
                - ONGRConnectionsBundle
        oxid:
            connection: oxid
            debug: "%kernel.debug%"
            mappings:
                - ONGROXIDConnectorBundle
                - ONGRDemoOXIDBundle
        translation:
            connection: default
            debug: true
            mappings:
                - ONGRTranslationsBundle

ongr_filter_manager:
    managers:
        product_list:
            filters:
                - category
                - wear_title
                - search
                - pager
                - sorting
            repository: 'es.manager.oxid.product'
    filters:
        choice:
            wear_title:
                request_field: 'title'
                field: title
        match:
            search:
                request_field: 'q'
                field: title
        document_field:
            category:
                request_field: 'document'
                field: categories
        pager:
            pager:
                request_field: 'page'
                count_per_page: 9
                max_pages: 10
        sort:
            sorting:
                request_field: 'sort'
                choices:
                    - { label: Price ascending, field: price, default: true }
                    - { label: Price descending, field: price, order: desc }
                    - { label: Title ascending, field: title }
                    - { label: Title descending, field: title, order: desc }

ongr_translations:
    managed_locales: ["lt", "de", "en"]
    repository: 'es.manager.translation.translation'
    
ongr_connections:
    active_shop: oxid
    shops:
        oxid:
            shop_id: 0
    sync:
        sync_storage:
            mysql:
                connection: default
                table_name: ongr_sync_storage

ongr_oxid:
    database_mapping:
        oxid:
            tags:
                @shop_tag: '_1'
                @lang_tag: ''
            shop_id: 0
            lang_id: 0
    entity_namespace: ONGROXIDConnectorBundle
